//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIUB_Task.DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cupon
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Perchentage { get; set; }
        public Nullable<System.DateTime> Expire_date { get; set; }
        public string Status { get; set; }
    }
}
